import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ShieldCheck } from 'lucide-react';
import CodeBlock from '../components/docs/CodeBlock';
import FeatureCard from '../components/docs/FeatureCard';
export default function ProductionBehavior() {
    return (_jsxs("div", { className: "docs-prose", children: [_jsx("p", { className: "text-sm text-zinc-500", children: "How It Works" }), _jsx("h1", { children: "Production Behavior" }), _jsx("p", { children: "How findchange behaves when deployed to production." }), _jsxs("div", { className: "flex items-start gap-3 p-4 rounded-card border border-accent/30 bg-accent/5 my-4", children: [_jsx(ShieldCheck, { size: 18, className: "text-accent shrink-0 mt-0.5" }), _jsxs("p", { className: "!mb-0", children: ["In production (", _jsx("code", { children: "NODE_ENV === 'production'" }), "), all hooks and components are no-ops with zero side effects."] })] }), _jsx("h2", { id: "dev-vs-prod", children: "Development vs Production" }), _jsxs("div", { className: "grid md:grid-cols-2 gap-4 my-6 not-prose", children: [_jsxs("div", { className: "rounded-card border border-border bg-bg-surface p-4", children: [_jsx("h3", { className: "text-sm font-semibold text-green-400 mb-2", children: "Development" }), _jsxs("ul", { className: "text-sm text-zinc-400 space-y-1 list-disc list-inside", children: [_jsxs("li", { children: [_jsx("code", { children: "useDebugState" }), " registers value in DebugStore"] }), _jsxs("li", { children: [_jsx("code", { children: "<DebugWatcher />" }), " renders floating button"] }), _jsx("li", { children: "Popup window available and synced" }), _jsx("li", { children: "BroadcastChannel and postMessage active" })] })] }), _jsxs("div", { className: "rounded-card border border-border bg-bg-surface p-4", children: [_jsx("h3", { className: "text-sm font-semibold text-zinc-400 mb-2", children: "Production" }), _jsxs("ul", { className: "text-sm text-zinc-400 space-y-1 list-disc list-inside", children: [_jsxs("li", { children: [_jsx("code", { children: "useDebugState" }), " returns value as-is (passthrough)"] }), _jsxs("li", { children: [_jsx("code", { children: "<DebugWatcher />" }), " renders ", _jsx("code", { children: "null" })] }), _jsx("li", { children: "No popup window, no side effects" }), _jsx("li", { children: "Zero bundle impact" })] })] })] }), _jsx("h2", { id: "same-code", children: "Same Code, Both Environments" }), _jsx("p", { children: "Your code stays identical in both environments. No conditional imports needed:" }), _jsx(CodeBlock, { code: `// Same code works in both dev and production
import { useDebugState, DebugWatcher } from 'findchange';

// Dev: tracked in debug window | Prod: passthrough, no-op
useDebugState('user', user);

// Dev: renders floating button | Prod: renders nothing
<DebugWatcher />`, filename: "App.tsx" }), _jsx("h2", { id: "no-config", children: "No Build Config Needed" }), _jsx("div", { className: "mt-4 not-prose", children: _jsx(FeatureCard, { icon: ShieldCheck, title: "No build config needed", description: "No babel plugins, no environment-specific imports, no webpack config. Just works out of the box." }) }), _jsxs("p", { className: "mt-4", children: ["The ", _jsx("code", { children: "isDevelopment()" }), " utility checks ", _jsx("code", { children: "process.env.NODE_ENV" }), " which is replaced at build time by all major bundlers (Vite, webpack, Rollup, etc.), so the production dead-code elimination removes all debug logic automatically."] })] }));
}
